server:
  port: 8188
github:
  client:
    id: 4e0a88af43d38b9738b6
    secret: a17ca55a89a8295a9c96969c6667adb6839e6303
    uri: http://localhost:8188/callback
  redirect:
    uri: http://localhost:8188/callback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcom?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver